name: wimu
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - audioread=3.0.1=py312h7900ff3_1
  - black=24.4.0=py312h7900ff3_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py312h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.1=hef1e5e3_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.10.0=py312h06a4308_0
  - gettext=0.21.1=h27087fc_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py312h06a4308_0
  - joblib=1.2.0=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.3=py312h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - librosa=0.10.1=pyhd8ed1ab_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=hd590300_5
  - lightning=2.2.1=pyhd8ed1ab_0
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.42.0=py312h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.8.0=py312h06a4308_0
  - matplotlib-base=3.8.0=py312h526ad5a_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - mpg123=1.32.4=h59595ed_0
  - mpmath=1.3.0=py312h06a4308_0
  - msgpack-python=1.0.3=py312hdb19cb5_0
  - munkres=1.1.4=py_0
  - mypy=1.5.1=py312h06a4308_0
  - mypy_extensions=1.0.0=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py312h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numba=0.59.1=py312hacefee8_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.2.1=hd590300_1
  - packaging=23.2=py312h06a4308_0
  - pandas=2.2.1=py312h526ad5a_0
  - pathspec=0.10.3=py312h06a4308_0
  - pcre2=10.42=hebb0a14_0
  - pillow=10.2.0=py312h5eee18b_0
  - pip=23.3.1=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - pooch=1.7.0=py312h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.0.9=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=4_cp312
  - pytorch=2.2.2=py3.12_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.2.1=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - qt-main=5.15.2=h7358343_9
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py312h06a4308_1
  - scikit-learn=1.3.0=py312h526ad5a_2
  - scipy=1.12.0=py312hc5e2394_0
  - seaborn=0.12.2=py312h06a4308_0
  - setuptools=68.2.2=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.3.7=py312hc7c0aa3_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.2.2=py312_cu121
  - torchmetrics=1.3.2=pyhd8ed1ab_0
  - torchvision=0.17.2=py312_cu121
  - tornado=6.3.3=py312h5eee18b_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing-extensions=4.9.0=py312h06a4308_1
  - typing_extensions=4.9.0=py312h06a4308_1
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py312h06a4308_1
  - wheel=0.41.2=py312h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.22.2
      - miditok==3.0.2
      - mido==1.3.2
      - omegaconf==2.3.0
      - pretty-midi==0.2.10
      - protobuf==4.25.3
      - psutil==5.9.8
      - pysmartdl==1.3.4
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - symusic==0.4.4
      - tokenizers==0.15.2
      - types-requests==2.31.0.20240406
      - wandb==0.16.6
